language: node_js
node_js:
  - "4.2.4"

addons:
  firefox: "43.0.4"

before_script:
  - npm install -g bower
  - bower install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./node_modules/protractor/bin/webdriver-manager update
  - gulp serve &
  - sleep 3 # give webserver some time to start

script:
  - >
    echo "Extracting firefox and setting PATH variable..."
    tar -xjf /tmp/firefox-43.0.tar.bz2 --directory /tmp
    export PATH="/tmp/firefox:$PATH"
    echo "Using firefox version `firefox --version`"

  - npm test

after_success:
  - npm run coveralls
  - npm run codacy

notifications:
  - email: false

sudo: false
